CREATE PROCEDURE [Portfolio].[Product.Create]
	@Name NVARCHAR(MAX),
	@BrandId UNIQUEIDENTIFIER
AS
BEGIN 
	IF @Name = '' OR @Name IS NULL
		SELECT @Name = NULL
	IF @BrandId IS NULL
		SELECT @BrandId = NULL
	BEGIN TRY
		INSERT INTO [Portfolio].[Product] ([Name], [BrandId])
        VALUES(@Name, @BrandId);
	END TRY
	BEGIN CATCH
		IF @BrandId IS NULL
			THROW 50000, 'BRAND_ID_IS_NOT_VALID', 1
		IF @Name IS NULL
			THROW 50001, 'PRODUCT_NAME_NOT_SPECIFIED', 1
	END CATCH
END;
