CREATE TABLE [Portfolio].[Brand]
(
    [Id]   UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Brand_Id] DEFAULT NEWID(),
    [Name] NVARCHAR(MAX)    NOT NULL,

    CONSTRAINT [PK_Brand] PRIMARY KEY ([Id])
);